
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";


// function Scene() {
//     const gltf = useLoader(GLTFLoader, '/AJ_BLACK_walking_macos_emb_1.gltf')
//     return <primitive object={gltf.scene} />
//   }
  
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/AJ_BLACK_walking_macos_emb_3.gltf"
  );
  const { actions } = useAnimations(animations, group);
  
  useEffect(() => {
    actions.web_walking_rmx1.play()
    // console.log(actions)
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" scale={6.995}>
          <skinnedMesh
            name="Allen003"
            geometry={nodes.Allen003.geometry}
            material={materials["AJ BLACK"]}
            skeleton={nodes.Allen003.skeleton}
          />
          <primitive object={nodes.ROOT} />
          <primitive object={nodes["ctrl-pole-legL"]} />
          <primitive object={nodes["ctrl-footL"]} />
          <primitive object={nodes["ctrl-footR"]} />
          <primitive object={nodes["ctrl-pole-legR"]} />
        </group>
        <group
          name="yamaha_rmx1_walking"
          position={[2.134, 8.052, -0.757]}
          rotation={[1.482, 0.559, -1.577]}
          scale={1.986}
        >
          <mesh
            name="Cube068"
            castShadow
            receiveShadow
            geometry={nodes.Cube068.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            name="Cube068_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube068_1.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube009_Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Cube011.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube010_Cube012"
            castShadow
            receiveShadow
            geometry={nodes.Cube010_Cube012.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube011_Cube013"
            castShadow
            receiveShadow
            geometry={nodes.Cube011_Cube013.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube012_Cube014"
            castShadow
            receiveShadow
            geometry={nodes.Cube012_Cube014.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube013_Cube015"
            castShadow
            receiveShadow
            geometry={nodes.Cube013_Cube015.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube014_Cube016"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_Cube016.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube015_Cube017"
            castShadow
            receiveShadow
            geometry={nodes.Cube015_Cube017.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube016_Cube018"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_Cube018.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube017_Cube019"
            castShadow
            receiveShadow
            geometry={nodes.Cube017_Cube019.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube018_Cube020"
            castShadow
            receiveShadow
            geometry={nodes.Cube018_Cube020.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube019_Cube021"
            castShadow
            receiveShadow
            geometry={nodes.Cube019_Cube021.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube020_Cube022"
            castShadow
            receiveShadow
            geometry={nodes.Cube020_Cube022.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube021_Cube023"
            castShadow
            receiveShadow
            geometry={nodes.Cube021_Cube023.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube022_Cube024"
            castShadow
            receiveShadow
            geometry={nodes.Cube022_Cube024.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube023_Cube025"
            castShadow
            receiveShadow
            geometry={nodes.Cube023_Cube025.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube024_Cube026"
            castShadow
            receiveShadow
            geometry={nodes.Cube024_Cube026.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube025_Cube027"
            castShadow
            receiveShadow
            geometry={nodes.Cube025_Cube027.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube026_Cube028"
            castShadow
            receiveShadow
            geometry={nodes.Cube026_Cube028.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube027_Cube029"
            castShadow
            receiveShadow
            geometry={nodes.Cube027_Cube029.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube028_Cube030"
            castShadow
            receiveShadow
            geometry={nodes.Cube028_Cube030.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube029_Cube031"
            castShadow
            receiveShadow
            geometry={nodes.Cube029_Cube031.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube030_Cube032"
            castShadow
            receiveShadow
            geometry={nodes.Cube030_Cube032.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube031_Cube033"
            castShadow
            receiveShadow
            geometry={nodes.Cube031_Cube033.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube069"
            castShadow
            receiveShadow
            geometry={nodes.Cube069.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube070"
            castShadow
            receiveShadow
            geometry={nodes.Cube070.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube071"
            castShadow
            receiveShadow
            geometry={nodes.Cube071.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube072"
            castShadow
            receiveShadow
            geometry={nodes.Cube072.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube073"
            castShadow
            receiveShadow
            geometry={nodes.Cube073.geometry}
            material={materials.None}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube074"
            castShadow
            receiveShadow
            geometry={nodes.Cube074.geometry}
            material={materials["Material.011"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube075"
            castShadow
            receiveShadow
            geometry={nodes.Cube075.geometry}
            material={materials["Material.011"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cube076"
            castShadow
            receiveShadow
            geometry={nodes.Cube076.geometry}
            material={materials["Material.011"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cylinder001_Cylinder002"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Cylinder002.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cylinder002_Cylinder003"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Cylinder003.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cylinder003_Cylinder004"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_Cylinder004.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cylinder008"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008.geometry}
            material={materials["Material.012"]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/AJ_BLACK_walking_macos_emb_3.gltf");