"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function NoHead(props) {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3dModels/noneck2(walking shot).glb')
  const { actions } = useAnimations(animations, group)

  

  useEffect(() => void (actions.walking_idle.reset().play().paused = false), [])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rig" position={[0, 0, 0.47]} rotation={[0, 0.067, 0]}>
          <skinnedMesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials.Material}
            skeleton={nodes.Cube.skeleton}
          />
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/noneck2(walking shot).glb')
