"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function OBModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3dModels/OB_OC2_8_5.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => void (actions.OBrunning.reset().play().paused = false), [])
  console.log(animations);
  

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="outside_border">
        <group name="Armature" position={[0, 4.116, 0.177]} rotation={[0.114, 0, 0]}>
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials.body}
            skeleton={nodes.body.skeleton}
          />
          <skinnedMesh
            name="hood"
            geometry={nodes.hood.geometry}
            material={materials.hoodie}
            skeleton={nodes.hood.skeleton}
          />
          <skinnedMesh
            name="left_pocket"
            geometry={nodes.left_pocket.geometry}
            material={materials['Material.001']}
            skeleton={nodes.left_pocket.skeleton}
          />
          <skinnedMesh
            name="NurbsPath044"
            geometry={nodes.NurbsPath044.geometry}
            material={materials.hair}
            skeleton={nodes.NurbsPath044.skeleton}
          />
          <skinnedMesh
            name="poncho"
            geometry={nodes.poncho.geometry}
            material={materials.poncho}
            skeleton={nodes.poncho.skeleton}
          />
          <skinnedMesh
            name="right_pocket"
            geometry={nodes.right_pocket.geometry}
            material={materials.Material}
            skeleton={nodes.right_pocket.skeleton}
          />
          <primitive object={nodes.ROOT} />
          <primitive object={nodes['CTRL-FOOTL']} />
          <primitive object={nodes['CTRL-FOOTR']} />
        </group>
        <group name="hair_empty" position={[0, 7.798, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/OB_OC2_8_5.glb')
